apiVersion: v1
kind: Secret
metadata:
  name: telegram-credentials
type: Opaque
data:
  TELEGRAM_BOT_TOKEN: ODgwMjc3MzMyOTpBQUV4VkN6eGo1VkgwUUc4SDZUaGtmdVJ0ZldmRzlXMXZ3bw==
  TELEGRAM_CHAT_ID: NjEwOTE3NTg4MA==